AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dynamic DNS Provider
Resources:
  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.put
      Runtime: python3.6
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /register/{subdomain}
            Method: PUT
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
  Table:
    Type: AWS::Serverless::SimpleTable
