AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dynamic DNS Provider
Resources:
  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.update
      Runtime: python3.6
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /update/{subdomain}
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          ZONE_ID: !Ref Zone
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.register
      Runtime: python3.6
      CodeUri: ./src
      Policies:
        - AmazonDynamoDBReadOnlyAccess
        - AmazonRoute53FullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /register/{subdomain}
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          ZONE_ID: !Ref Zone
  Table:
    Type: AWS::Serverless::SimpleTable
  Zone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: "ibidns.com."
