AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  DynDNSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      CodeUri: ./
      Events:
        DynDNSApi:
          Type: Api
          Properties:
            Path: /DynDNS
            Method: GET
